<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <TargetFrameworks>net472;net8</TargetFrameworks>
	<LangVersion>8</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>  

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)src\NetTopologySuite.IO.Oracle\NetTopologySuite.IO.Oracle.csproj" />
  </ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<Reference Include="System.Configuration" />
	</ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8'">
	  <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Update="nunit" Version="4.3.2" />
    <PackageReference Update="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition=" '$(TargetFramework)' == 'net8' ">
    <Copy SourceFiles="App.config" DestinationFiles="$(OutDir)\testhost.dll.config" />
  </Target>
  
</Project>
