name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore NetTopologySuite.IO.Oracle.sln
    - name: Build
      run: dotnet build NetTopologySuite.IO.Oracle.sln --no-restore
    - name: Pull and run latest Oracle XE
      run: docker pull gvenzl/oracle-xe:latest
    - name: Run Oracle XE docker image
      run: docker run -d -p 1521:1521 -e ORACLE_PASSWORD=oracle gvenzl/oracle-xe
    - name: Test
      run: dotnet test NetTopologySuite.IO.Oracle.sln --no-build --verbosity normal
